### ISSUE TITLE
no dist

### ISSUE THREAD

**Issue by GeniusTDY** [fuegovic/LibreChat-Windows-Installer#4]
![image](https://github.com/fuegovic/LibreChat-Windows-Installer/assets/108384914/6b5fee08-2a8f-4d93-96e3-5b2b8160a325)
But there is no "dist" folder, and after creating a new "dist" folder under the "client" folder and copying the files under "client" to "dist", the webpage will be blank when opened.

**Comment by fuegovic** [comment]
Looks like something went wrong during the install process. The scripts I made aren't the best at handling problems. 

Open the cmd prompt in the d:\librechat folder and try this:
- `npm ci`
- `npm run frontend`
- `npm run backend`    <- this command should then properly start librechat if everything goes well

Let me know how it goes!

**Comment by GeniusTDY** [comment]
Thanks, it seems to be running normally.
